name: pyqg_tlh
channels:
# for pyfftw
#  - mforbes # old, doesn't support 3.5
#  - nanshe # broke
  - conda-forge
dependencies:
  - python=3.5
  - numpy
  - scipy
  - cython
  - pyfftw
  - pytest
  - future
  - pip:
    - git+https://github.com/tlhsieh/pyqg@master
    - codecov
    - pytest-cov
